### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by Indeserpen** [ahhh/Stego_Dropper#2]
Hello when i run stego.py i get error:
mage to embed a payload: pwned.PNG
Payload to embed in image: finaln.exe
Name of the image to output: pwnedout.png
Traceback (most recent call last):
  File "stego.py", line 60, in <module>
    main()
  File "stego.py", line 56, in main
    hide_payload(opts.input_img, opts.payload, opts.output_img)
  File "stego.py", line 14, in hide_payload
    carrier = cv.LoadImage(input_img)
IOError: [Errno 2] No such file or directory: 'pwned.PNG'

pwned.png is in same directory! 

Other question should i use payload .bin format and image should be .png format?

**Comment by Indeserpen** [comment]
All working fine image was without extension and .bin raw works all fine! Nice work!
